let formFieldName =
    [

        {
            divClass: "form-group col-12 col-sm-6 col-md-6",
            labelClass: "",
            labelFor: "first_name",
            labelText: "Name *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "first_name",
            inputType: "text",
            inputName: "first_name",
            errorName: "first_name",
            errorClass: "",
            valueName: "first_name",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "phone",
            labelText: "Phone *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "phone",
            inputType: "text",
            inputName: "phone",
            errorName: "phone",
            errorClass: "",
            valueName: "phone",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "email",
            labelText: "Email *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "email",
            inputType: "text",
            inputName: "email",
            errorName: "email",
            errorClass: "",
            valueName: "email",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-6",
            chieldDivClass: "custom-file",
            labelClass: "custom-file-label",
            labelFor: "image",
            labelText: " P.S/Vill/Road/House",
            placeholder: "",
            inputClass: "custom-file-input ",
            inputId: "image",
            inputType: "file",
            inputName: "image",
            errorName: "image",
            errorClass: "",
            valueName: "image",
            type: "file"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "password",
            labelText: "Password *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "password",
            inputType: "password",
            inputName: "password",
            errorName: "password",
            errorClass: "",
            valueName: "password",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "confPassword",
            labelText: "Confirm Password *",
            placeholder: "",
            inputClass: "form-control is-valid",
            inputId: "confPassword",
            inputType: "password",
            inputName: "confPassword",
            errorName: "confPassword",
            errorClass: "",
            valueName: "confPassword",
            type: "text"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "bloodGroup",
            labelText: "Blood Group *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "bloodGroup",
            inputType: "",
            inputName: "bloodGroup",
            errorName: "bloodGroup",
            errorClass: "",
            valueName: "bloodGroup",
            type: "select"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "occupation",
            labelText: "Occupation",
            placeholder: "",
            inputClass: "form-control",
            inputId: "occupation",
            inputType: "text",
            inputName: "occupation",
            errorName: "occupation",
            errorClass: "",
            valueName: "occupation",
            type: "text"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "occupationAddress",
            labelText: "Occupation Address",
            placeholder: "",
            inputClass: "form-control",
            inputId: "occupationAddress",
            inputType: "text",
            inputName: "occupationAddress",
            errorName: "occupationAddress",
            errorClass: "",
            valueName: "occupationAddress",
            type: "text"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "fbId",
            labelText: "Facebook Link",
            placeholder: "",
            inputClass: "form-control",
            inputId: "fbId",
            inputType: "text",
            inputName: "fbId",
            errorName: "fbId",
            errorClass: "",
            valueName: "fbId",
            type: "text"
        },
        {
            block: "SSC Information"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "sscBoard",
            labelText: "Board*",
            placeholder: "",
            inputClass: "form-control",
            inputId: "sscBoard",
            inputType: "",
            inputName: "sscBoard",
            errorName: "sscBoard",
            errorClass: "",
            valueName: "sscBoard",
            type: "select",

        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "sscRoll",
            labelText: "Roll No *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "sscRoll",
            inputType: "text",
            inputName: "sscRoll",
            errorName: "sscRoll",
            errorClass: "",
            valueName: "sscRoll",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "sscReg",
            labelText: "Registration No *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "sscRoll",
            inputType: "text",
            inputName: "sscRoll",
            errorName: "sscRoll",
            errorClass: "",
            valueName: "sscRoll",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "sscInstitute",
            labelText: "Institute Name *",
            placeholder: "",
            inputClass: "form-control",
            inputId: "sscInstitute",
            inputType: "text",
            inputName: "sscInstitute",
            errorName: "sscInstitute",
            errorClass: "",
            valueName: "sscInstitute",
            type: "text"
        },
        {
            block: "HSC Information"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "hscBoard",
            labelText: "Board",
            placeholder: "",
            inputClass: "form-control",
            inputId: "hscBoard",
            inputType: "",
            inputName: "hscBoard",
            errorName: "hscBoard",
            errorClass: "",
            valueName: "hscBoard",
            type: "select",
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "hscRoll",
            labelText: "Roll No ",
            placeholder: "",
            inputClass: "form-control",
            inputId: "hscRoll",
            inputType: "text",
            inputName: "hscRoll",
            errorName: "hscRoll",
            errorClass: "",
            valueName: "hscRoll",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "hscReg",
            labelText: "Registration No ",
            placeholder: "",
            inputClass: "form-control",
            inputId: "hscReg",
            inputType: "text",
            inputName: "hscReg",
            errorName: "hscReg",
            errorClass: "",
            valueName: "hscReg",
            type: "text"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "hscInstitute",
            labelText: "Institute Name ",
            placeholder: "",
            inputClass: "form-control",
            inputId: "hscInstitute",
            inputType: "text",
            inputName: "hscInstitute",
            errorName: "hscInstitute",
            errorClass: "",
            valueName: "hscInstitute",
            type: "text"
        },
        {
            block: "Permanent Address"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "perDivission",
            labelText: "Divission",
            placeholder: "",
            inputClass: "form-control",
            inputId: "perDivission",
            inputType: "",
            inputName: "perDivission",
            errorName: "perDivission",
            errorClass: "",
            valueName: "perDivission",
            type: "select"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "perDistrict",
            labelText: "District",
            placeholder: "",
            inputClass: "form-control",
            inputId: "perDistrict",
            inputType: "",
            inputName: "perDistrict",
            errorName: "perDistrict",
            errorClass: "",
            valueName: "perDistrict",
            type: "select"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "perPoliceStatin",
            labelText: "Police Station",
            placeholder: "",
            inputClass: "form-control",
            inputId: "perPoliceStatin",
            inputType: "",
            inputName: "perPoliceStatin",
            errorName: "perPoliceStatin",
            errorClass: "",
            valueName: "perPoliceStatin",
            type: "select"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "perPoVillRoadHouse",
            labelText: " P.O/Vill/Road/House",
            placeholder: "",
            inputClass: "form-control",
            inputId: "perPoVillRoadHouse",
            inputType: "text",
            inputName: "perPoVillRoadHouse",
            errorName: "perPoVillRoadHouse",
            errorClass: "",
            valueName: "perPoVillRoadHouse",
            type: "text"
        },
        {
            block: "Present Address"
        }, {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "country",
            labelText: "Country",
            placeholder: "",
            inputClass: "form-control",
            inputId: "country",
            inputType: "",
            inputName: "country",
            errorName: "country",
            errorClass: "",
            valueName: "country",
            type: "select"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "preDivission",
            labelText: "Divission",
            placeholder: "",
            inputClass: "form-control",
            inputId: "preDivission",
            inputType: "",
            inputName: "preDivission",
            errorName: "preDivission",
            errorClass: "",
            valueName: "preDivission",
            type: "select"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "preDistrict",
            labelText: "District",
            placeholder: "",
            inputClass: "form-control",
            inputId: "preDistrict",
            inputType: "",
            inputName: "preDistrict",
            errorName: "preDistrict",
            errorClass: "",
            valueName: "preDistrict",
            type: "select"
        },
        {
            divClass: "form-group col-12 col-sm-6 col-md-3",
            labelClass: "",
            labelFor: "prePsPoVillRoadHouse",
            labelText: " P.S/P.O/Vill/Road/House",
            placeholder: "",
            inputClass: "form-control",
            inputId: "prePsPoVillRoadHouse",
            inputType: "text",
            inputName: "prePsPoVillRoadHouse",
            errorName: "prePsPoVillRoadHouse",
            errorClass: "",
            valueName: "prePsPoVillRoadHouse",
            type: "text"
        }

    ];

export { formFieldName };